glslangValidator -D -V -S vert -e main hlsl/sprite_vert.hlsl -o ../../../aether3d_build/Samples/sprite_vert.spv
glslangValidator -D -V -S frag -e main hlsl/sprite_frag.hlsl -o ../../../aether3d_build/Samples/sprite_frag.spv
glslangValidator -D -V -S vert -e main hlsl/unlit_cube_vert.hlsl -o ../../../aether3d_build/Samples/unlit_cube_vert.spv
glslangValidator -D -V -S frag -e main hlsl/unlit_cube_frag.hlsl -o ../../../aether3d_build/Samples/unlit_cube_frag.spv
glslangValidator -D -V -S vert -e main hlsl/unlit_vert.hlsl -o ../../../aether3d_build/Samples/unlit_vert.spv
glslangValidator -D -V -S frag -e main hlsl/unlit_frag.hlsl -o ../../../aether3d_build/Samples/unlit_frag.spv
glslangValidator -D -V -S vert -e main hlsl/unlit_skin_vert.hlsl -o ../../../aether3d_build/Samples/unlit_skin_vert.spv
glslangValidator -D -V -S vert -e main hlsl/moments_vert.hlsl -o ../../../aether3d_build/Samples/moments_vert.spv
glslangValidator -D -V -S vert -e main hlsl/moments_skin_vert.hlsl -o ../../../aether3d_build/Samples/moments_skin_vert.spv
glslangValidator -D -V -S frag -e main hlsl/moments_frag.hlsl -o ../../../aether3d_build/Samples/moments_frag.spv
glslangValidator -D -V -S vert -e main hlsl/skybox_vert.hlsl -o ../../../aether3d_build/Samples/skybox_vert.spv
glslangValidator -D -V -S frag -e main hlsl/skybox_frag.hlsl -o ../../../aether3d_build/Samples/skybox_frag.spv
glslangValidator -D -V -S vert -e main hlsl/depthnormals_vert.hlsl -o ../../../aether3d_build/Samples/depthnormals_vert.spv
glslangValidator -D -V -S frag -e main hlsl/depthnormals_frag.hlsl -o ../../../aether3d_build/Samples/depthnormals_frag.spv
glslangValidator -D -V -S comp -e CSMain hlsl/LightCuller.hlsl -o ../../../aether3d_build/Samples/LightCuller.spv
glslangValidator -D -V -S vert -e main hlsl/Standard_vert.hlsl -o ../../../aether3d_build/Samples/Standard_vert.spv
glslangValidator -D -V -S frag -e main hlsl/Standard_frag.hlsl -o ../../../aether3d_build/Samples/Standard_frag.spv
glslangValidator -D -V -S comp -e CSMain hlsl/Bloom.hlsl -o ../../../aether3d_build/Samples/Bloom.spv
glslangValidator -D -V -S comp -e CSMain hlsl/Blur.hlsl -o ../../../aether3d_build/Samples/Blur.spv

