UNAME := $(shell uname)
COMPILER := g++ -g
ENGINE_LIB := libaether3d_linux.a
LIBS := -ldl -lxcb -lxcb-ewmh -lxcb-keysyms -lxcb-icccm -lX11-xcb -lX11 -lGL -lopenal

ifeq ($(UNAME), Darwin)
COMPILER := clang++ -fsanitize=address
ENGINE_LIB := libaether3d_osx.a
LIBS := -framework IOKit -framework OpenAL -framework Cocoa -framework OpenGL -framework QuartzCore
endif

ifeq ($(OS),Windows_NT)
ENGINE_LIB := libaether3d_win.a
LIBS := -lOpenAL32 -lOpenGL32 -lgdi32
endif

all:
	$(COMPILER) -std=c++11 03_Simple3D.cpp ../Core/Matrix.cpp -I../Include -o 03_Simple3D ../../../aether3d_build/$(ENGINE_LIB) $(LIBS)

